version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.3.0

jobs:
  build:
    docker:
      - image: cimg/node:18.17   # CircleCI Node.js image
    steps:
      - checkout                 # Pull your repo code
      - run:
          name: Install server dependencies
          command: cd server && npm install

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - sonarcloud/scan:
          projectKey: $SONAR_PROJECT_KEY
          organization: $SONAR_ORGANIZATION
