version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17   # CircleCI Node.js image
    steps:
      - checkout                 # Pull your repo code
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install sonar-scanner
          command: npm install -g sonar-scanner
      - run:
          name: Run SonarCloud Scan
          command: |
           cd server && sonar-scanner \
              -Dsonar.projectKey=$riaancarelse17 \
              -Dsonar.organization=$riaancarelse17 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
