version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17   # CircleCI Node.js image
    steps:
      - checkout                 # Pull your repo code
      - run:
          name: Install server dependencies
          command: cd server && npm install

  sonarcloud:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest   # Official SonarScanner CLI image
    steps:
      - checkout
      - run:
          name: Run SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.qualitygate.wait=true

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - sonarcloud:
          requires:
            - build
